apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      automountServiceAccountToken: false
      containers:
      - name: user-service
        image: pavithrasambath2003/user-service:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 256Mi
          limits:
            memory: 256Mi
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        envFrom:
        - configMapRef:
            name: medicojob-config
        - secretRef:
            name: medicojob-secrets



